### ISSUE TITLE
Allow list of tasks to be customized

### ISSUE THREAD

**Issue by jonabc** [maxbeizer/home_maintenance#2]
First off, so much 💖  for creating the action.  I really appreciate all of the ways GitHub and actions can be used outside of write code -> find bug -> bang head on wall -> fix bug -> write code -> find bug -> ... 😆 

What would you think about letting users provide their own list of maintenance chores to do each year, or in some other way customize the list?  Some of the listed tasks don't apply to my property and I'd like to use the action without getting issues opened for tasks that don't apply.

**Comment by maxbeizer** [comment]
Sounds great. Perhaps a way to do this would be allow some sort of path to file as part of the action config? I don't think that would be too hard. I'll hack on it some next weekend. Thanks @jonabc !

**Comment by TheSalesOpsGuy** [comment]
I know actions can read markdown files so perhaps have it point at a `TaskList.md` file in a specific folder?

**Comment by maxbeizer** [comment]
done via #3  HTH 💖
